Remove yarn tsc from the dockerfile as it is done before by the workflow and because xwe got: error TS18003: No inputs were found in config file '/opt/app-root/src/tsconfig.json'
Signed-off-by: cmoulliard <cmoulliard@redhat.com>